import { writeFile } from "node:fs/promises";
import { draftFollowUp, draftReply } from "../lib/ai-replies";
import { seedReplyContext } from "../lib/eval-ai";
import { SALES_PERSONA } from "../lib/sales-persona";
import { playbook } from "../lib/sales-playbook";

/** Regenerates AI_REPLY_LIBRARY.md from the live reply engine so documentation never drifts from behaviour. */
const scenarios: Array<[string, string[]]> = [
  ["First greeting", ["Hello", "namaste hajur", "नमस्ते"]],
  ["Restaurant price", ["How much is Aadhar POS for my restaurant?", "restaurant ko lagi price kati ho?", "रेस्टुरेन्टको लागि मूल्य कति हो?"]],
  ["Retail price", ["What does the POS cost for my retail shop?", "mero kirana pasal ko lagi kati parcha?", "पसलको लागि कति पर्छ?"]],
  ["Hardware", ["Do you sell printers and barcode scanners?", "printer ra scanner ko price?", "प्रिन्टर पनि दिनुहुन्छ?"]],
  ["Unknown business type", ["What's your price?", "price kati ho?", "मूल्य कति हो?"]],
  ["Specific package", ["How much is the Growth package for a cafe?", "cafe ko lagi growth package kati?", "क्याफेको लागि ग्रोथ प्याकेज कति?"]],
  ["Negotiation", ["Growth package final price?", "Growth package final kati?", "ग्रोथ प्याकेजको अन्तिम मूल्य कति?"]],
  ["Price objection", ["It's too expensive for us", "alik mahango bhayo", "धेरै महँगो भयो"]],
  ["Demo request", ["Can I see a demo for my restaurant?", "restaurant ko demo pathaunu", "रेस्टुरेन्टको डेमो देखाउनुहोस्"]],
  ["Meeting", ["Can we schedule a call tomorrow?", "bhetnu milcha?", "भेट्नु मिल्छ?"]],
  ["Proposal / ready to buy", ["Please send me a quotation", "proposal pathaunu", "प्रस्ताव पठाउनुहोस्"]],
  ["Payment", ["Okay send payment details", "QR send garnu, proceed garam", "भुक्तानी कसरी गर्ने?"]],
  ["Unverified feature", ["Does it support KOT printing for my restaurant?", "restaurant ma KOT milcha?", "रेस्टुरेन्टमा किचन टिकट मिल्छ?"]],
  ["Multi-branch", ["Does Enterprise support multi branch?", "3 ota branch ko lagi milcha?", "धेरै शाखाको लागि मिल्छ?"]],
  ["VAT / IRD", ["Is your software IRD approved?", "bill ma VAT lagcha?", "भ्याट लाग्छ?"]],
  ["Offline", ["Can it work offline? Internet is weak here", "internet gayo bhane chalcha?", "इन्टरनेट बिना चल्छ?"]],
  ["Hotel", ["Do you have a hotel system with room booking?", "hotel ko lagi system cha?", "होटलको लागि सिस्टम छ?"]],
  ["Website / ecommerce", ["Do you build websites?", "website banaidinu huncha?", "वेबसाइट बनाउनुहुन्छ?"]],
  ["Instagram shop", ["We sell 500+ products on Instagram, too many DMs", "instagram ma bechchhau, stock milaunu garo", "इन्स्टाग्राममा बेच्छौं"]],
  ["Training / migration", ["Will you train my staff?", "purano data excel bata import garna milcha?", "तालिम दिनुहुन्छ?"]],
  ["Support", ["What support do you give after sales?", "problem aayo bhane support milcha?", "समस्या आयो भने सपोर्ट छ?"]],
  ["Later", ["Maybe after Dashain", "pachi kura garaula", "दशैं पछि कुरा गरौं"]],
  ["Not interested", ["Not interested, thanks", "malai chahidaina", "चाहिँदैन"]],
  ["Opt-out", ["Stop messaging me", "message nagarnu aba", "फेरि सम्पर्क नगर्नु"]],
  ["Complaint", ["The system is not working since morning", "billing chaldaina", "सफ्टवेयर चल्दैन"]],
  ["Are you a bot?", ["Are you a bot?", "timi ko ho?", "तपाईं को हो?"]],
  ["Unclear", ["??", "tyo kura heram", "हम्म"]],
];
const context = seedReplyContext();
const lines = [
  "# Aayatra AI reply library",
  "",
  "Generated by `npx tsx scripts/generate-reply-library.ts` from the live reply engine (`lib/ai-replies.ts`, `lib/sales-playbook.ts`). Do not edit by hand: change the engine, re-run, and the evaluation suite re-checks every reply.",
  "",
  "Prices are the owner-approved poster prices (OWNER_APPROVED_POSTER_2026). Features use the seeded feature-claim register, where restaurant features are still UNKNOWN until the dimsum source is audited — so feature answers say the team will confirm. Once a feature is VERIFIED_AVAILABLE with approved wording, the reply changes automatically.",
  "",
  "## How the assistant talks",
  "",
  "```text", SALES_PERSONA, "```",
  "",
  "## Replies by scenario",
  "",
  "Legend: **Human** = a person must review before sending or take over; **Auto-safe** = wording is safe to send as-is if the owner enables automatic replies and a provider is configured.",
  "",
];
for (const [title, messages] of scenarios) {
  lines.push(`### ${title}`, "");
  for (const message of messages) {
    const draft = draftReply(message, context);
    lines.push(`**Customer (${draft.language === "NE" ? "Nepali" : draft.language === "NE_ROMAN" ? "Romanized Nepali" : "English"}):** ${message}  `);
    lines.push(`_Intent ${draft.intent} · stage ${draft.temperature} · ${draft.requiresHuman ? "Human" : draft.autoSendEligible ? "Auto-safe" : "Review"}${draft.nextActions.length ? ` · next: ${draft.nextActions.join(", ")}` : ""}_  `);
    lines.push(draft.body ? `**Aayatra:** ${draft.body}` : "**Aayatra:** _(no reply — opt-out recorded, follow-ups stopped)_");
    if (draft.escalationReasons.length) lines.push("", `> Escalation: ${draft.escalationReasons.join("; ")}`);
    lines.push("");
  }
}
lines.push("## Follow-up nudges (drafted for approval, max 3, stop on reply/opt-out)", "");
for (const temperature of ["WARM", "INTERESTED", "HOT", "READY_TO_BUY", "NEGOTIATING", "PROPOSAL_SENT", "PAYMENT_PENDING"] as const) {
  lines.push(`**${temperature}**`, "", `- EN: ${draftFollowUp(temperature, "EN", 1)}`, `- Romanized: ${draftFollowUp(temperature, "NE_ROMAN", 1)}`, `- नेपाली: ${draftFollowUp(temperature, "NE", 1)}`, "");
}
lines.push("## Objection playbook (§37)", "", "| Topic | Objection | Strategy | Never claim | Human |", "|---|---|---|---|---|");
for (const topic of playbook) lines.push(`| ${topic.key} | ${topic.objectionType ?? "—"} | ${topic.strategy} | ${topic.prohibitedClaims.join(", ") || "—"} | ${topic.requiresHuman ? "Yes" : "No"} |`);
await writeFile("AI_REPLY_LIBRARY.md", `${lines.join("\n")}\n`);
console.log("AI_REPLY_LIBRARY.md written");
